### ISSUE TITLE
ERR_STRING_TOO_LONG

### ISSUE THREAD

**Issue by munegowda** [cmdcolin/interproscan2genome#1]
Hi Colin,

I get the following error when I try it with my test data:

![image](https://github.com/user-attachments/assets/a7119823-202e-49a2-952c-155b1efe1ee3)

**Comment by cmdcolin** [comment]
thanks for reporting this...I just published a new version that tries to solve this

I think you can re-run "npm install -g interproscan2genome" and then re-try

**Comment by munegowda** [comment]
Thank you. I now run into another error:

![image](https://github.com/user-attachments/assets/97a12ad6-4de7-4986-9f08-4a04ee3c33a0)

**Comment by munegowda** [comment]
Ah, I just realized that the GFF3 output from InterProScan5 contains sequence as well in FASTA format (https://interproscan-docs.readthedocs.io/en/latest/OutputFormats.html#generic-feature-format-version-3-gff3). I deleted everything in the GFF3 file except for the information in GFF3 format.

I now get out of memory related error:

![image](https://github.com/user-attachments/assets/a06d1edf-35b9-49f0-8182-8407cac8e8af)

**Comment by cmdcolin** [comment]
how large are your files? you might be able to increase node memory allocation (it is pretty small by default) but ideally i want the program to not take up too much memory....

**Comment by munegowda** [comment]
The gene annotation file is 58MB while the InterProScan GFF3 file is 2.4GB.

**Comment by cmdcolin** [comment]
## Option 1

If you have a machine with a good amount of memory, you can try making

"NODE_OPTIONS=--max-old-space-size=8000  interproscan2genome --genomeGFF genes.gff --interproGFF domains.gff > domainsOnTheGenome.gff"  #8000 is ~8Gb of memory, can maybe even go higher

## Option 2

You can split up your interpro GFF into smaller pieces. you should be able to split it at basically arbitrary places, because there is probably not "child-parent" relationships in it. this might be a good option for now

## Option 3

I can also try to make the program more memory efficient...might take some time though

**Comment by munegowda** [comment]
Option 1 seems to work for me. There are no error messages but the output file domainsOnTheGenome.gff is empty.

**Comment by cmdcolin** [comment]
would you be able to upload the gene annotation GFF and maybe a snippet of the interpro GFF? the program tries to associate the  ID= from column 9 from the genomeGFF with column 1 of the interproGFF

if these are not matching, then it will be empty

**Comment by cmdcolin** [comment]
Thanks for sending your data  files! I made another update. You can re-download the latest with npm install -g interproscan2genome and retry

**Comment by cmdcolin** [comment]
the amount of annotations from interpro is pretty high and it's hard to see what the identifiers mean but after running it looks like this for me

![image](https://github.com/user-attachments/assets/82828892-00e8-4548-a714-6a50d9446fdb)

**Comment by munegowda** [comment]
Everything works now. Thanks Colin!
